#!/usr/bin/env bash
# This script displays the content of the current directory cutting the prefix before the first dash
for file in *; do
    if [ -e "$file" ]; then
        echo "${file#*-}"
    fi
done
